image: golang:1.14.3

variables:
  # Please edit to your GitLab project
  REPO_NAME: github.com/felixrosatmetlla/audiodsplib


before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
  - dependencies
  - build
  - test

dependencies:
  stage: dependencies
  script:
    - go install github.com/felixrosatmetlla/audiodsplib/audiodsputils

build:
  stage: build
  script:
    - go build -v ./...
    
unit_tests:
  stage: test
  script:
    - go get -u github.com/jstemmer/go-junit-report

    - go test -v ./... | go-junit-report > report.xml

coverage:
  stage: test
  script:
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/t-yuki/gocover-cobertura

    - go test -coverprofile=coverage.txt -covermode count ./...
    - gocover-cobertura < coverage.txt > coverage.xml

  artifacts:
    reports:
      junit: report.xml
      cobertura: coverage.xml
    
